ardalis/Specification

Ardalis.Specification.sln, Specification.EF/src/Ardalis.Specification.EF/Ardalis.Specification.EF.csproj, Specification.EF/src/Ardalis.Specification.EF/IRepositoryBase.cs, Specification.EF/src/Ardalis.Specification.EF/RepositoryBase.cs, Specification.EF/src/Ardalis.Specification.EF/SpecificationEvaluator.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Ardali.Specification.EF.IntegrationTests.csproj, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Address.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Company.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Country.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/LoggerFactoryProvider.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Product.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Repository.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Seeds/AddressSeed.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Seeds/CompanySeed.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Seeds/CountrySeed.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Seeds/ProductSeed.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Seeds/StoreSeed.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/Store.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Data/TestDbContext.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/SpecificationTestBase.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/SpecificationTests.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Specs/CompanyWithStoresThenIncludeAddressSpec.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Specs/CompanyWithStoresThenIncludeProductsSpec.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Specs/StoreWithAddressAndProductsSpec.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Specs/StoreWithAddressSpec.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Specs/StoreWithProductsSpec.cs, Specification.EF/tests/Ardali.Specification.EF.IntegrationTests/Specs/StoreWithProductsUsingStringSpec.cs
This PR should be merged after PR #30
Once it is merged, the projects might have to be revisited for small fixes in order to compile successfully. 
One possible conflict that might happen is the namespace "Ardalis.Specification" and the spec class "Specification".
=> Add EF plugin project with integration tests.

ArdalisSpecification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs, ArdalisSpecification/src/Ardalis.Specification/ISpecification.cs, ArdalisSpecification/src/Ardalis.Specification/Specification.cs, ArdalisSpecification/src/Ardalis.Specification/SpecificationEvaluatorBase.cs, ArdalisSpecification/tests/Ardalis.Specification.IntegrationTests/SampleSpecs/PostsByBlogPaginatedSpec.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/ParameterReplacerVisitor.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/SearchExtension.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/SpecificationEvaluator.cs
The feature is described in #38 
Note: The search group implementation remains as it is. If anyone has idea how to improve the syntax, let me know and give me a hint, so we can change that.
=> Implementation for "Search" feature.

Ardalis.Specification.sln, sample/Ardalis.SampleApp.Core/Entitites/CustomerAggregate/Customer.cs, sample/Ardalis.SampleApp.Core/Entitites/Seeds/CustomerSeed.cs, sample/Ardalis.SampleApp.Core/Specifications/CustomerByNameSpec.cs, sample/Ardalis.SampleApp.Core/Specifications/CustomerByNameWithStoresSpec.cs, sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs, sample/Ardalis.SampleApp.Web/Controllers/CustomersController.cs, sample/Ardalis.SampleApp.Web/Pages/Index.cshtml, sample/Ardalis.SampleApp.Web/Pages/Index.cshtml.cs, sample/Ardalis.SampleApp.Web/Program.cs, sample/Ardalis.SampleApp.Web/Startup.cs
Added a home page to the sample to show a Customer
Added logging to show if caching is working
=> Added example of caching with specification

ArdalisSpecification/src/Ardalis.Specification/IRepositoryBase.cs
Added xml comments for IRepositoryBase.
=> Started #33.

ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBase.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Fixture/Repository.cs, sample/Ardalis.SampleApp.Core/Interfaces/IRepository.cs, sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs, sample/Ardalis.SampleApp.Infrastructure/Data/MyRepository.cs
#33 
Added  /// <inheritdoc/> to derived types of IRepositoryBase<T>.
=> Added comments for protected methods of RepositoryBase.

ArdalisSpecification/src/Ardalis.Specification/Builder/IIncludeAggregator.cs, ArdalisSpecification/src/Ardalis.Specification/Builder/IncludeAggregator.cs, ArdalisSpecification/src/Ardalis.Specification/IRepositoryBase.cs, ArdalisSpecification/src/Ardalis.Specification/ISpecification.cs, ArdalisSpecification/src/Ardalis.Specification/OrderTypeEnum.cs, ArdalisSpecification/src/Ardalis.Specification/Specification.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBase.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Fixture/Repository.cs, sample/Ardalis.SampleApp.Core/Interfaces/IRepository.cs, sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs, sample/Ardalis.SampleApp.Infrastructure/Data/MyRepository.cs
See #33.
Added docs to:
- IIncludeAggregator
- ISpecification
- OrderTypeEnum
=> Added some more documentation.

ArdalisSpecification/src/Ardalis.Specification/ISpecificationEvaluator.cs, ArdalisSpecification/src/Ardalis.Specification/SpecificationEvaluatorBase.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/SpecificationEvaluator.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/SearchExtension.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/SpecificationEvaluator.cs
See #33 
Added docs to:
-SearchExtension
-ISpecificationEvaluator
-types derived from ISpecificationEvaluator
=> Added comments for SearchExtension

ArdalisSpecification/src/Ardalis.Specification/IRepositoryBaseOfT.cs, ArdalisSpecification/src/Ardalis.Specification/ISingleResultSpecification.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/CompanyByIdIncludeStoresThenIncludeAddressSpec.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/CompanyByIdIncludeStoresThenIncludeProductsSpec.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/CompanyByIdSpec.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoreByIdIncludeAddressAndProductsSpec.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoreByIdIncludeAddressSpec.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoreByIdIncludeProductsSpec.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoreByIdIncludeProductsUsingStringSpec.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBaseOfT.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Fixture/SharedDatabaseFixture.cs, sample/Ardalis.SampleApp.Core/Specifications/CustomerByNameSpec.cs, sample/Ardalis.SampleApp.Core/Specifications/CustomerByNameWithStoresSpec.cs, sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs
- Added ISingleResultSpecification marker interface 
- Refactored `GetBySpec` method of the generic repository.
- Refactored test fixtures and the sample app.
=> Added ISingleResultSpecification marker interface.

ArdalisSpecification/src/Ardalis.Specification/ISpecification.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/BuilderTests/SpecificationBuilderExtensions_AsNoTracking.cs, ArdalisSpecification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/CompanyByIdAsUntrackedSpec.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/RepositoryOfT_GetBySpec.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/RepositoryOfT_ListAsync.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Repository_GetBySpec.cs, ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Repository_ListAsync.cs
See: https://github.com/ardalis/Specification/issues/73#issuecomment-789280108
=> Migrate AsNoTracking tests to efcore 5.0

docs/usage/create-specifications.md
"How to Create Specifications" docs page under "Usage"
=> create specifications docs page

docs/usage/create-specifications.md
added ISingleResultSpecification documentation to "How to Create Specifications" under "Usage"
=> add ISingleResultSpecification documentation

docs/features/base-features.md, docs/features/orderby.md, docs/features/paging.md, docs/features/skip.md, docs/features/take.md, docs/features/where.md
added docs for skip, take, and paging
=> skip, take, and paging docs

ArdalisSpecification/src/Ardalis.Specification/IReadRepositoryBase.cs, ArdalisSpecification/src/Ardalis.Specification/IRepositoryBaseOfT.cs, ArdalisSpecificationEF/src/Ardalis.Specification.EF/RepositoryBaseOfT.cs, sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs
- Added cancellation token for the async methods
- Added constraint for `GetById` method, `where TId : notnull`
=> Added cancellationToken for repository's async methods.

docs/features/select.md, docs/getting-started/faq.md
this PR adds a doc for Select and also adds its usage to the FAQ
=> Select doc page

docs/getting-started/quick-start-guide.md
Hi Steve,
thanks for the package. I just saw the quick start guide is yet to come. So I thought this version is better than nothing. If you have not planned to write a version soon, just rejected this PR.
best regards, Jan
=> It's a start

.github/workflows/build-test-ef6.yml, .github/workflows/build-test.yml
Updated build workflows for manual and pr triggering.
=> update build workflows

Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs, Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/RepositoryOfT_AnyAsync.cs, Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs, Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/RepositoryOfT_AnyAsync.cs, Specification/src/Ardalis.Specification/IReadRepositoryBase.cs, sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs
Implementation of the issues #180 and #181.
=> Implemented AnyAsync method

Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Extensions/DbSetExtensions.cs, docs/usage/use-specification-dbcontext.md, docs/usage/use-specification-repository-pattern.md, sample/Ardalis.SampleApp.Core/Interfaces/IAggregateRoot.cs, sample/Ardalis.SampleApp.Core/Interfaces/ICustomerRepository.cs, sample/Ardalis.SampleApp.Core/Specifications/CustomerByNameWithStoresSpec.cs, sample/Ardalis.SampleApp.Core/Specifications/CustomerSpec.cs, sample/Ardalis.SampleApp.Core/Specifications/PaginationHelper.cs, sample/Ardalis.SampleApp.Infrastructure/DataAccess/SampleDbContext.cs, sample/Ardalis.SampleApp.Web/Interfaces/ICustomerUiService.cs, sample/Ardalis.SampleApp.Web/Program.cs, sample/Ardalis.SampleApp.Web/Startup.cs
- adding documentation to satisfy #201
- adding documentation to patially satisfy #202 for using Specifications with DbContexts
- cleanup using unnecessary statements found while navigating code
=> Update docs for use with DbContext and Repository Pattern

Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs, Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs, Specification/src/Ardalis.Specification/IRepositoryBaseOfT.cs
=> Return Task<int> from SaveChangesAsync.

Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
=> use DbSet Update method in repo Update method

docs/features/ignorequeryfilters.md, docs/usage/use-built-in-abstract-repository.md, docs/usage/use-specification-repository-pattern.md
=> Update abstract repository documentation

docs/features/evaluate.md
=> Update Evaluate documentation

Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Extensions/DbSetExtensions.cs, Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Extensions/DbSetExtensions.cs
=> Add WithSpecification overload for specifications with Select.

Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Extensions/SearchExtension.cs
=> Update the search feature to generate parameterized query.

Specification/src/Ardalis.Specification/IEntity.cs
=> Remove IEntity contract.

Directory.Packages.props
=> Revise EF Core dependencies per TFM.

src/Ardalis.Specification/Builders/Builder_Cache.cs, tests/Ardalis.Specification.Tests/Builders/Builder_Cache.cs
=> Add WithCacheKey extensions.

docs/index.md
=> Docs - Overview page

docs/getting-started/quick-start-guide.md
=> Docs - QuickStart page

docs/getting-started/faq.md, docs/related-resources/articles.md, docs/related-resources/patterns-used.md, docs/related-resources/podcasts.md, docs/related-resources/training.md, docs/related-resources/videos.md
Fixes #313 
Fixes #158 
- Updated FAQ page
- Move `Pattern Used` page to `Related Resources` folder.
=> Docs - FAQ
