ardalis/Specification

- src/Ardalis.Specification/BaseSpecification.cs
- src/Ardalis.Specification/EfSpecificationEvaluator.cs
- src/Ardalis.Specification/ISpecification.cs
- tests/Ardalis.Specification.IntegrationTests/SampleClient/EfRepository.cs
- tests/Ardalis.Specification.IntegrationTests/SampleSpecs/BlogNamesSpecification.cs
- tests/Ardalis.Specification.IntegrationTests/SampleSpecs/PostSelectSpecification.cs
The PR presents just another way to solve issues with selector functionality in the specification.
We keep selector evaluation within specification logic, and not delegating to the repository.
> Improving the selector functionality.

- src/Ardalis.Specification/BaseSpecification.cs
- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/SpecificationEvaluator.cs
Allow adding multiple criterias in the constructor body, by calling AddCriteria(criteria) method.
This would offer the following advantages
- Adding criteria (where clause) based on some condition.
- Adding multiple conditions in more clean fashion, instead of using "&" in a long expression as a constructor parameter.
In addition, having parameterless constructor, would offer creating empty specifications. This might be quite useful feature. Whenever we need list of all records, we can start with empty specification. If afterward, we require some global filter for particular entity, we can add the criteria in the empty specification.
> Allow adding multiple criterias.

- src/Ardalis.Specification/BaseSpecification.cs
- src/Ardalis.Specification/EfSpecificationEvaluator.cs
- tests/Ardalis.Specification.IntegrationTests/DatabaseCommunicationTestBase.cs
- tests/Ardalis.Specification.IntegrationTests/DatabaseCommunicationTests.cs
- tests/Ardalis.Specification.IntegrationTests/SampleClient/EfRepository.cs
- tests/Ardalis.Specification.IntegrationTests/SampleSpecs/BlogNamesSpecification.cs
- tests/Ardalis.Specification.IntegrationTests/SampleSpecs/PostSelectSpecification.cs
- tests/Ardalis.Specification.IntegrationTests/SelectorTests.cs
Hi @ardalis 
I added the missing parts and the integration tests for the selector.
Let me describe shortly the functionality:
- The intention was not only adding the selector functionality in the specification, but also keeping the evaluation of the same within the specification (not delegating it out to the EFRepository).
- Select always returns new type. That's why need new inherited infrastructure containing the output type.
- Adding new List method in EFRepository would just confuse the users. Therefore, the method is overloaded, and based on the fact if specification contains a selector or not, the appropriate method will be utilized.
> Consolidating the selector functionality.

- src/Ardalis.Specification/Ardalis.Specification.csproj
- src/Ardalis.Specification/BaseSpecification.cs
- src/Ardalis.Specification/EfSpecificationEvaluator.cs
- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/SpecificationEvaluator.cs
- tests/Ardalis.Specification.IntegrationTests/Ardalis.Specification.IntegrationTests.csproj
- tests/Ardalis.Specification.IntegrationTests/SampleClient/Author.cs
- tests/Ardalis.Specification.IntegrationTests/SampleClient/Blog.cs
- tests/Ardalis.Specification.IntegrationTests/SampleClient/EfRepository.cs
- tests/Ardalis.Specification.IntegrationTests/SampleClient/Post.cs
- tests/Ardalis.Specification.IntegrationTests/SampleClient/SampleDbContext.cs
- tests/Ardalis.Specification.IntegrationTests/SampleSpecs/BlogNamesSpecification.cs
- tests/Ardalis.Specification.IntegrationTests/SampleSpecs/PostsByBlogOrderedByThenBySpec.cs
- tests/Ardalis.Specification.UnitTests/Ardalis.Specification.UnitTests.csproj
- tests/Ardalis.Specification.UnitTests/QueryExtensions/Include/Entities/Book.cs
- tests/Ardalis.Specification.UnitTests/QueryExtensions/Include/Entities/Person.cs
- tests/Ardalis.Specification.UnitTests/QueryExtensions/Include/IncludeAggregatorTests.cs
- tests/Ardalis.Specification.UnitTests/QueryExtensions/Include/IncludeQueryTests.cs
- tests/Ardalis.Specification.UnitTests/QueryExtensions/Include/IncludeVisitorTests.cs
- tests/Ardalis.Specification.UnitTests/SpecificationImplementationEvaluatorGetQuery.cs
Enable C# 8.0 Nullable Reference Types for the following projects
1)  Ardalis.Specification
2)  Ardalis.Specification.IntegrationTests
3)  Ardalis.Specification.UnitTests
Locally I tested both unit test and integration test and looks like all test passed successfully!
@ardalis  Please take a look.
> Enable nullable reference types

- ArdalisSpecification/src/Ardalis.Specification/Builder/IIncludableSpecificationBuilder.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/IOrderedSpecificationBuilder.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/ISpecificationBuilder.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/IncludableBuilderExtensions.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/IncludableSpecificationBuilder.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/OrderedBuilderExtensions.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/OrderedSpecificationBuilder.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/SpecificationBuilder.cs
- ArdalisSpecification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- ArdalisSpecification/src/Ardalis.Specification/IRepositoryBase.cs
- ArdalisSpecification/src/Ardalis.Specification/ISpecification.cs
- ArdalisSpecification/src/Ardalis.Specification/Specification.cs
- ArdalisSpecification/src/Ardalis.Specification/SpecificationEvaluatorBase.cs
- ArdalisSpecificationEF/src/Ardalis.Specification.EF/Ardalis.Specification.EntityFrameworkCore.csproj
The internal builder infrastructure is refactored. No breaking API changes for end users.
Now, everything can be written in one large chain. You can go back after Then definitions, and continue building the specification.
This is first from a series of PRs. But we need this restructuring, in order to PR the new features.
```
public class StoresOrderedSpecByName : Specification<Store>
{
public StoresOrderedSpecByName()
{
Query.Where(x => x.Name == "something")
.Include(x => x.Company)
.ThenInclude(x => x.Stores)
.Include(x => x.Address)
.OrderBy(x => x.Name)
.ThenBy(x => x.Id)
.Skip(2)
.Take(10);
}
}
```
> Internal builder refactoring. Chaining improvements.

- ArdalisSpecificationEF/src/Ardalis.Specification.EF/SearchExtension.cs
The automatic addition of "%" wildcards is removed from the search evaluator. The users can add their own wildcards while defining the specification. This way, the `Search` functionality can be used for queries where you need some complex wildcard usage.
As for querying substrings, using a LINQ `Contains()` method is good enough. I might have been in delusion all this time. I remember clearly that in certain scenarios Contains() couldn't be translated, but can't remember the cases now :). 
Anyhow, now users have an alternative way of doing things.
> Allow users to define their own wildcards for Search feature.

- ArdalisSpecification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- ArdalisSpecification/src/Ardalis.Specification/ISpecification.cs
- ArdalisSpecification/src/Ardalis.Specification/Specification.cs
- ArdalisSpecificationEF/src/Ardalis.Specification.EF/SpecificationEvaluator.cs
- ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/SpecificationTests.cs
- ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Specs/CompanyAsUntrackedSpec.cs
- ArdalisSpecificationEF/tests/Ardalis.Specification.EF.IntegrationTests/Specs/CompanySpec.cs
This PR provides `AsNoTracking()` as an extension for `Query` in a `Specification`.
The test itself is a bit tricky. Initially dbcontext tracks all entities as they are seeded. This requires me to fetch the record and detach it from the context first.
On EFCore5 this would be more easily done with `dbcontext.ChangeTracker.Clear();`
>  Add "AsNoTracking" feature. (#71)

- ArdalisSpecification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
This is a small change, it fixes the nullability warnings. The expression parameter of the OrderBy extension should be defined as `Expression<Func<T, object?>> orderExpression`. So, in the specification, we can use `Query.OrderBy(x => x.Name)` and we don't have to use ! to avoid the warnings.
During the evaluation, the name of the property is retrieved from the given expression, the value is not of any importance. Accepting nullable object does not impact anything.
> Updated expression paremeter for OrderBy extension.

- docs/usage/create-specifications.md
note added about additional operators, so people aren't confused into thinking where is the only operator that can be used. 
Also fixed top level heading.
> Create specification advanced

- docs/features/base-features.md
- docs/features/orderby.md
orderby documentation, along with orderbydescending, thenby, and thenbydescending
also changed baseFeatures table of contents to show pages in proper order
> orderby doc

- ArdalisSpecification/src/Ardalis.Specification/ISingleResultSpecificationOfT.cs
Added interface `ISingleResultSpecification<T>` to use `ISpecification<T>` + `ISingleResultSpecification` without generic constraints.
This fixes #126
> added interface ISingleResultSpecification<T>

- .github/workflows/build-test-ef6.yml
- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- .github/workflows/publishef6.yml
- .github/workflows/publishefcore.yml
- Ardalis.Specification.sln
- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Ardalis.Specification.EntityFramework6.csproj
- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/Ardalis.Specification.EntityFramework6.IntegrationTests.csproj
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests.csproj
- Specification/src/Ardalis.Specification/Ardalis.Specification.csproj
- Specification/src/Ardalis.Specification/Builder/SpecificationBuilder.cs
- Specification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- Specification/src/Ardalis.Specification/Specification.cs
- Specification/tests/Ardalis.Specification.UnitTests/Ardalis.Specification.UnitTests.csproj
- sample/Ardalis.SampleApp.Core/Ardalis.SampleApp.Core.csproj
- sample/Ardalis.SampleApp.Infrastructure/Ardalis.SampleApp.Infrastructure.csproj
- sample/Ardalis.SampleApp.Web/Ardalis.SampleApp.Web.csproj
- Updated dotnet SDKs to 5.0.x in all GitHub workflows
- Updated Nuget package dependencies for all projects.
Once the PR is merged, the following packages will be updated to v5.2.0. Not sure if we can do it all at once like this. I don't know how Nuget behaves in case EF plugin packages are published before the base package. Hopefully we can :)
- Ardalis.Specification
- Ardalis.Specification.EntityFrameworkCore
- Ardalis.Specification.EntityFramework6
Fixes #147
> Update packages to version 5.2.0

- docs/extensions/create-specification-builder.md
- docs/features/caching.md
- docs/index.md
Work in progress. Does this look okay?  
Or should the docs contain less code and move that into the sample projects in stead?
> Docs builder extensions #162

- Specification/src/Ardalis.Specification/Builder/CacheSpecificationBuilder.cs
- Specification/src/Ardalis.Specification/Builder/ICacheSpecificationBuilder.cs
- Specification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
A small change to the `SpecificationBuilderExtensions.EnableCache` builder method in order to allow developers to create their own extension methods for customized caching implementations.
I've been using Spefications throughout several different projects and am a huge fan. We've recently added support for caching in our repositories and I've refactored the code so it integrates with Specification. A requirement in our project was to have some expiration date on the cache, which isn't possible with the current method signatures. I saw two possibilities:
1. Create additional methods/overloads/... in Ardalis.Specification that allow for adding information on how the caching should behave.
2. Minimal intrusion in Ardalis.Specification by changing the return type of …
> ICacheSpecificationBuilder

- Specification/src/Ardalis.Specification/Builder/OrderedBuilderExtensions.cs
- Specification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- Specification/src/Ardalis.Specification/Evaluators/OrderEvaluator.cs
- Specification/src/Ardalis.Specification/Evaluators/SearchEvaluator.cs
- Specification/src/Ardalis.Specification/Evaluators/WhereEvaluator.cs
- Specification/src/Ardalis.Specification/Expressions/IncludeExpressionInfo.cs
- Specification/src/Ardalis.Specification/Expressions/OrderExpressionInfo.cs
- Specification/src/Ardalis.Specification/Expressions/SearchExpressionInfo.cs
- Specification/src/Ardalis.Specification/Expressions/WhereExpressionInfo.cs
- Specification/src/Ardalis.Specification/ISpecification.cs
- Specification/src/Ardalis.Specification/Specification.cs
> Refactor specification expressions

- Specification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- Specification/src/Ardalis.Specification/Exceptions/DuplicateSkipException.cs
- Specification/src/Ardalis.Specification/Exceptions/DuplicateTakeException.cs
- Specification/src/Ardalis.Specification/ISpecification.cs
- Specification/src/Ardalis.Specification/Specification.cs
- Specification/tests/Ardalis.Specification.UnitTests/BuilderTests/SpecificationBuilderExtensions_Skip.cs
- Specification/tests/Ardalis.Specification.UnitTests/BuilderTests/SpecificationBuilderExtensions_Take.cs
- Specification/tests/Ardalis.Specification.UnitTests/EvaluatorTests/InMemorySpecificationEvaluatorTests.cs
- Specification/tests/Ardalis.Specification.UnitTests/ExceptionTests/DuplicateSkipExceptionTests.cs
- Specification/tests/Ardalis.Specification.UnitTests/ExceptionTests/DuplicateTakeExceptionTests.cs
- Specification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoresPaginatedSpec.cs
- Specification/tests/Ardalis.Specification.UnitTests/IncludeExpressionInfoTests.cs
I removed the obsolete Paginate method from issue [Remove obsolete Paginate builder action.](https://github.com/ardalis/Specification/issues/189).
Hope this change was sufficient.
> Remove paginate

- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/IgnoreQueryFiltersEvaluator.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
- Specification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- Specification/src/Ardalis.Specification/ISpecification.cs
- Specification/src/Ardalis.Specification/Specification.cs
- Specification/tests/Ardalis.Specification.UnitTests/BuilderTests/SpecificationBuilderExtensions_IgnoreQueryFilters.cs
- Specification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/CompanyByIdIgnoreQueryFilters.cs
> Implement IgnoreQueryFilters feature.

- docs/usage/use-specification-inmemory-collection.md
- add documentation for evaluating specifications to in memory collection #205
> Update specification with in memory collections documentation

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Evaluators/SpecificationEvaluator.cs
- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/RepositoryOfT_GetBySpec.cs
Throw SelectorNotFound exception from the specification evaluator, and not from the repository. Users may have their own repository implementation, and ensuring the selector exists is crucial, so having the check in the evaluator is better.
> Move the selector checks to the evaluators.

- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/AsNoTrackingWithIdentityResolutionEvaluator.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/AsSplitQueryEvaluator.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
Some of the ORM features are not available in `EF Core 3`, so we've been using preprocessor directives. The condition was fine, but now that we added additional TFM `net6.0`, they're excluded from it as well.
```c#
public SpecificationEvaluator(bool cacheEnabled = false)
{
this.evaluators.AddRange(new IEvaluator[]
{
WhereEvaluator.Instance,
SearchEvaluator.Instance,
cacheEnabled ? IncludeEvaluator.Cached : IncludeEvaluator.Default,
OrderEvaluator.Instance,
PaginationEvaluator.Instance,
AsNoTrackingEvaluator.Instance,
IgnoreQueryFiltersEvaluator.Instance,
#if NETSTANDARD2_1
AsSplitQueryEvaluator.Instance,
AsNoTrackingWithIdentityResolutionEvaluator.Instance
#endif
});
}
```
So, instead of `#if NETSTANDARD2_1`, we should use negation `#if !NETSTANDARD2_0`.
> Fix preprocessor directives in EF Core project to account for net6.0

- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/CachedReadConcurrentDictionary.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/IncludeEvaluator.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Extensions/SearchExtension.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests.csproj
- Specification/src/Ardalis.Specification/Ardalis.Specification.csproj
- Specification/src/Ardalis.Specification/IReadRepositoryBase.cs
- Specification/tests/Ardalis.Specification.UnitTests/Ardalis.Specification.UnitTests.csproj
The PR includes:
- The language version is updated to 9.0 for the following packages:
- Ardalis.Specification (TFM: netstandard2.0)
- Ardalis.Specification.EntityFrameworkCore (TFM: netstandard2.0, netstandard2.1, net6.0) 
- Fixed nullability warnings.
Closes #215
> Fix nullability warnings.

- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/RepositoryOfT_AnyAsync.cs
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/RepositoryOfT_AnyAsync.cs
There were a misleading on the test name description, saying it should return true but in fact it was expected a false result.
Also, the files EOL were modified  from CRLF to LF.
> Fixed test name description

- Specification/src/Ardalis.Specification/ISpecification.cs
- Specification/src/Ardalis.Specification/Specification.cs
> Add dictionary as arbitrary state for specifications.

- docs/extensions/create-specification-builder.md
- docs/extensions/extend-specification-builder.md
- docs/features/caching.md
Simplify docs after changes proposed in #248
> Docs: Simplify example on specification builder extensiblity

- Specification/src/Ardalis.Specification/ISpecification.cs
- Specification/src/Ardalis.Specification/Specification.cs
> Add support for updating specifications.

- Specification/src/Ardalis.Specification/Specification.cs
We had a few requests for this. Frankly, there is no reason for them to be abstract, we're not requiring any contract in them. So, now users can create empty specifications simply by using `new Specification<T>()`. I have seen some interesting generic designs by users, and this would be of help to them.
> Updated base specifications as non-abstract classes.

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Ardalis.Specification.EntityFramework6.csproj
- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/Ardalis.Specification.EntityFramework6.IntegrationTests.csproj
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests.csproj
- Specification/src/Ardalis.Specification/Ardalis.Specification.csproj
- Specification/tests/Ardalis.Specification.UnitTests/Ardalis.Specification.UnitTests.csproj
- sample/Ardalis.SampleApp.Core/Ardalis.SampleApp.Core.csproj
- sample/Ardalis.SampleApp.Infrastructure/Ardalis.SampleApp.Infrastructure.csproj
- sample/Ardalis.SampleApp.Web/Ardalis.SampleApp.Web.csproj
Updated Nuget dependencies and updated version to 6.1.0
Changes:
- Added `AddRangeAsync`. [PR 239](https://github.com/ardalis/Specification/pull/239)
- Added dictionary as arbitrary state for specifications. [PR 248](https://github.com/ardalis/Specification/pull/248)
- Added support for updating specifications. [PR 251](https://github.com/ardalis/Specification/pull/251)
- Updated base specifications as non-abstract classes. [PR 252](https://github.com/ardalis/Specification/pull/252)
- Update the infrastructure for single result specifications. [PR 272](https://github.com/ardalis/Specification/pull/272)
- Added `UpdateRangeAsync`. [PR 272](https://github.com/ardalis/Specification/pull/272)
- Add WithSpecification overload for specifications with Select. [PR …
> Publish version 6.1.0

- docs/index.md
The `Just the Docs` project is now hosted somewhere else.
Change our links to it in the `Docs theme notes` section of our own docs.
Gotta start somewhere 😉
> Fix `Just the Docs` link in docs home page

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Evaluators/SpecificationEvaluator.cs
- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/RepositoryOfT_ListAsync.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/RepositoryOfT_ListAsync.cs
- Specification/src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- Specification/src/Ardalis.Specification/Evaluators/InMemorySpecificationEvaluator.cs
- Specification/src/Ardalis.Specification/Exceptions/ConcurrentSelectorsException.cs
- Specification/src/Ardalis.Specification/Exceptions/SelectorNotFoundException.cs
- Specification/src/Ardalis.Specification/ISpecification.cs
- Specification/src/Ardalis.Specification/Specification.cs
- Specification/tests/Ardalis.Specification.UnitTests/BuilderTests/SpecificationBuilderExtensions_SelectMany.cs
- Specification/tests/Ardalis.Specification.UnitTests/ExceptionTests/ConcurrentSelectorsExceptionTests.cs
- Specification/tests/Ardalis.Specification.UnitTests/ExceptionTests/SelectorNotFoundExceptionTests.cs
- Specification/tests/Ardalis.Specification.UnitTests/Fixture/Entities/Seeds/ProductSeed.cs
- Specification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoreProductNamesEmptySpec.cs
- Specification/tests/Ardalis.Specification.UnitTests/Fixture/Specs/StoreProductNamesSpec.cs
For issue https://github.com/ardalis/Specification/issues/294
Usage:
```c#
public class StoreProductNamesSpec : Specification<Store, string?>
{
public StoreProductNamesSpec()
{
Query.SelectMany(s => s.Products.Select(p => p.Name));
}
}
```
Concurrent usage of Select and SelectMany is prevented via a runtime evaluator exception.
We may want to rename `ISpecification<T, TResult>.Selector` to `SelectExpression` to match the newly added `SelectManyExpression` to be consistent (I couldn't come up with a good name other than SelectManyExpression).
Let me know how it looks - happy to make additional changes.
> Implement SelectMany support

- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/ContextFactoryRepositoryBaseOfT.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- Specification/src/Ardalis.Specification/Ardalis.Specification.csproj
- Specification/src/Ardalis.Specification/IReadRepositoryBase.cs
- sample/Ardalis.SampleApp.Core/Ardalis.SampleApp.Core.csproj
- sample/Ardalis.SampleApp.Infrastructure/Data/CachedCustomerRepository.cs
Moving forward we'll drop support for some old TFMs. The projects are updated as follows:
- `Ardalis.Specification` - multi-target, `net6.0` and `netstandard2.0` (required for EF6 plugin package).
- `Ardalis.Specification.EntityFrameworkCore` - `net6.0`
- `Ardalis.Specification.EntityFramework6` - `net472`
NOTE: These are just the minimum required versions. The same is true for the dependencies. For example, `EntityFrameworkCore` package depends on version `6.0.6`, but consumers are free to install the newer versions explicitly.
> Updated projects, drop support for old TFMs.

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Evaluators/SpecificationEvaluator.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
- Specification/src/Ardalis.Specification/Evaluators/InMemorySpecificationEvaluator.cs
closes #308 
The PR enables us to more easily extend the evaluators list. We have exposed the state as protected.
```csharp
public class MyPartialEvaluator : IEvaluator
{
private MyPartialEvaluator () { }
public static MyPartialEvaluator Instance { get; } = new MyPartialEvaluator();
public bool IsCriteriaEvaluator { get; } = true;
public IQueryable<T> GetQuery<T>(IQueryable<T> query, ISpecification<T> specification) where T : class
{
// Write your desired implementation
return query;
}
}
public class MySpecificationEvaluator : SpecificationEvaluator
{
public static MySpecificationEvaluator Instance { get; } = new MySpecificationEvaluator();
private MySpecificationEvaluator() : base()
{
Evaluators.Add(MyPartialEvaluator .Instance);
}
}
```
> Add support for extending default evaluator list

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/Ardalis.Specification.EntityFramework6.csproj
- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/Ardalis.Specification.EntityFramework6.IntegrationTests.csproj
- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/Fixture/SharedDatabaseFixture.cs
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests.csproj
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Fixture/SharedDatabaseFixture.cs
- docker-compose.yml
Closes #340 
Updated the `EntityFramework6` package to multi-target `net472` and `net6.0`. Apparently, there are folks that use EF6 from `.NET` projects.
> Add net6.0 TFM for EntityFramework6 package.

- Ardalis.Specification.sln
- sample/Ardalis.Sample.App1/WebApplicationExtensions.cs
- sample/Ardalis.Sample.App2/Program.cs
- sample/Ardalis.Sample.App2/WebApplicationExtensions.cs
- sample/Ardalis.Sample.App3/AppSpecificationEvaluator.cs
- sample/Ardalis.Sample.App3/Ardalis.Sample.App3.csproj
- sample/Ardalis.Sample.App3/IReadRepository.cs
- sample/Ardalis.Sample.App3/IRepository.cs
- sample/Ardalis.Sample.App3/PagedResponse.cs
- sample/Ardalis.Sample.App3/Pagination.cs
- sample/Ardalis.Sample.App3/PaginationSettings.cs
- sample/Ardalis.Sample.App3/Program.cs
- sample/Ardalis.Sample.App3/QueryTagEvaluator.cs
- sample/Ardalis.Sample.App3/RepositoryBase.cs
- sample/Ardalis.Sample.App3/WebApplicationExtensions.cs
- sample/Ardalis.Sample.App3/appsettings.Development.json
- sample/Ardalis.Sample.App3/appsettings.json
- sample/Ardalis.Sample.Domain/Specs/CustomerByIdSpec.cs
Closes #344 
Added more samples and improved the sample applications. Added various usages (single result spec, selectors, extensions, evaluators, paginated results, projections with Automapper, etc.). Added a lot of comments. 
I hope users will find this helpful.
> Add more samples.

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Ardalis.Specification.sln
- Specification/src/Ardalis.Specification/ISpecification.cs
- setup-sqllocaldb.ps1
The `Local DB` comes pre-installed for Windows hosts, but our tests are occasionally failing to establish a connection. Adding an explicit task might ensure the DB is up and ready before it continues with the next job. At least I think so :) Let's try it.
> Add script for SQL Local DB setup.

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- Specification/src/Ardalis.Specification/IReadRepositoryBase.cs
Super simple contribution but hopefully a helpful one.
I noticed the obsolete warnings when working in our organization's server repo and it took 15 minutes of research and git blame to find the commit where these were marked obsolete, study the code and determine what I should have been doing instead.
I figured I'd contribute to the project to save the next guy some time. Ardalis is a major backbone of our project so I hope this contribution helps. 🙂
> Add messages to obsolete specs for clarity

- Specification/src/Ardalis.Specification/Evaluators/SearchExtension.cs
- Specification/tests/Ardalis.Specification.UnitTests/EvaluatorTests/SearchExtension_Like.cs
> Fix InMemory SearchExtension bug

- Specification.EntityFramework6/src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- Specification.EntityFramework6/tests/Ardalis.Specification.EntityFramework6.IntegrationTests/Fixture/RepositoryOfT.cs
- Specification.EntityFrameworkCore/src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- Specification.EntityFrameworkCore/tests/Ardalis.Specification.EntityFrameworkCore.IntegrationTests/Fixture/RepositoryOfT.cs
- sample/Ardalis.Sample.App3/RepositoryBase.cs
> 397 make fields and methods protected

- .github/workflows/ci.yml
- .github/workflows/release.yml
- coverage.sh
- src/Ardalis.Specification.EntityFramework6/Ardalis.Specification.EntityFramework6.csproj
- src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- src/Ardalis.Specification/Ardalis.Specification.csproj
We've been using Windows hosts and LocalDb database for the CI workflows. That's mainly because of the EF6 package and `net472` target.
But it's not stable, and we have random fails. The connection to localDb fails because it's not always up and ready. We can mitigate the issue by waiting for the database to be ready before running the tests.
Anyhow instead of all that, since the EF6 package targets `net9.0` too; then let's just use ubuntu hosts and run tests using only `net9.0` runtime. We're using TestContainers, so we won't need localDb, we'll utilize the mssql container for the tests.
It's a bit of a risk not to run the tests for `net472` target, but it's a rarely changing package. And also we may always run it locally.
> Update GitHub workflows to use Linux hosts.

- Directory.Packages.props
- src/Ardalis.Specification/Builder/IncludableBuilderExtensions.cs
- src/Ardalis.Specification/Builder/OrderedBuilderExtensions.cs
- src/Ardalis.Specification/Builder/SpecificationBuilderExtensions.cs
- src/Ardalis.Specification/Evaluators/PaginationEvaluator.cs
- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/Specification.cs
- tests/Ardalis.Specification.Tests/Ardalis.Specification.Tests.csproj
- tests/Ardalis.Specification.Tests/Builders/Builder_Skip.cs
- tests/Ardalis.Specification.Tests/Builders/Builder_Take.cs
- tests/Ardalis.Specification.Tests/SpecificationSizeTests.cs
Fixes #415 #416 #417 #418 
TLDR: The size of an empty is reduced to 96 bytes, from 392 bytes.
> Reduce the size of specifications and avoid unnecessary memory allocations

- src/Ardalis.Specification.EntityFramework6/Extensions/IncludeExtensions.cs
- src/Ardalis.Specification/Builders/Builder_Include.cs
- src/Ardalis.Specification/Expressions/IncludeExpressionInfo.cs
- src/Ardalis.Specification/Expressions/OrderExpressionInfo.cs
- src/Ardalis.Specification/Expressions/SearchExpressionInfo.cs
- src/Ardalis.Specification/Expressions/WhereExpressionInfo.cs
> Simplify and minimize expression containers.

- src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- src/Ardalis.Specification.EntityFrameworkCore/ContextFactoryRepositoryBaseOfT.cs
- src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- src/Ardalis.Specification/IReadRepositoryBase.cs
- src/Ardalis.Specification/IRepositoryBase.cs
- tests/Ardalis.Specification.EntityFramework6.Tests/RepositoryOfT_GetBySpec.cs
Fixes #361 
Fixes #346 
- Removed the obsolete `GetBySpec` methods.
- The `Update` and `Delete` methods will return the number of state entries written to the database.
> Update repository methods.

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/IgnoreAutoIncludesEvaluator.cs
- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/TagWithEvaluator.cs
- src/Ardalis.Specification/Builders/Builder_Flags.cs
- src/Ardalis.Specification/Builders/Builder_TagWith.cs
- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/Specification.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/IgnoreAutoIncludesEvaluatorTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/TagWithEvaluatorTests.cs
- tests/Ardalis.Specification.Tests/Builders/Builder_IgnoreAutoIncludes.cs
- tests/Ardalis.Specification.Tests/Builders/Builder_TagWith.cs
- tests/Ardalis.Specification.Tests/SpecificationSizeTests.cs
> Add TagWith and IgnoreAutoIncludes features.

- README.md
- readme-nuget.md
Consolidated the Readme file.
- Removed the badge for total downloads. The shields.io badge no longer works properly, it reports old values.
- Removed the videos section. It's quite old content and may create confusion.
- Added short Releases section.
- Clean-up.
> Update Readme files.

- README.md
- src/Ardalis.Specification.EntityFramework6/Ardalis.Specification.EntityFramework6.csproj
- src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- src/Ardalis.Specification.EntityFrameworkCore/Ardalis.Specification.EntityFrameworkCore.csproj
- src/Ardalis.Specification.EntityFrameworkCore/ContextFactoryRepositoryBaseOfT.cs
- src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- src/Ardalis.Specification/Ardalis.Specification.csproj
- src/Ardalis.Specification/Evaluators/ISpecificationEvaluator.cs
- src/Ardalis.Specification/IEntity.cs
- src/Ardalis.Specification/IReadRepositoryBase.cs
- src/Ardalis.Specification/IRepositoryBase.cs
- src/Directory.Build.props
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Repositories/Repository_WriteTests.cs
- tests/Directory.Build.props
> Prepare for publish, version 9.0.0

- samples/Ardalis.Sample.App2/Program.cs
- src/Ardalis.Specification/Builders/Builder_Cache.cs
- src/Ardalis.Specification/Builders/Builder_Flags.cs
- src/Ardalis.Specification/Builders/Builder_Include.cs
- src/Ardalis.Specification/Builders/Builder_Order.cs
- src/Ardalis.Specification/Builders/Builder_Paging.cs
- src/Ardalis.Specification/Builders/Builder_Search.cs
- src/Ardalis.Specification/Builders/Builder_TagWith.cs
- src/Ardalis.Specification/Builders/Builder_Where.cs
- src/Ardalis.Specification/Builders/IncludableSpecificationBuilder.cs
- src/Ardalis.Specification/Builders/SpecificationBuilder.cs
- tests/Ardalis.Specification.EntityFramework6.Tests/RepositoryOfT_ListAsync.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Extensions/Extensions_WithSpecification.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/QueryTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Repositories/Repository_AnyTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Repositories/Repository_CountTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Repositories/Repository_FirstTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Repositories/Repository_ListTests.cs
> Re-add inheritance in the builders.

- exclusion.dic
- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/Specification.cs
- src/Ardalis.Specification/SpecificationExtensions.cs
- tests/Ardalis.Specification.Tests/SpecificationExtensionsTests.cs
> Add WithProjectionOf feature.

- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/IncludeEvaluatorTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Fixture/Data/Bar.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Fixture/TestDbContext.cs
> Add tests for ThenInclude with TPH inheritance strategy.

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/IncludeEvaluator.cs
- src/Ardalis.Specification/Builders/Builder_Include.cs
- src/Ardalis.Specification/Expressions/IncludeExpressionInfo.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/IncludeEvaluatorTests.cs
- tests/Ardalis.Specification.Tests/Expressions/IncludeExpressionInfoTests.cs
Fixes #463 
There is an ongoing inconsistency in EF (described in the related issue). For now, we won't infer the previous property type from LambdaExpression, we'll keep it as a state in `IncludeExpressionInfo`.
The constructors of the `IncludeExpressionInfo` are modified, so that might be a breaking change for anyone using it directly.
> Fix type inference for ThenInclude with casting.

- docs/.devcontainer/README.md
- docs/.devcontainer/devcontainer.json
- docs/.devcontainer/dockerfile
- docs/.gitignore
- docs/Gemfile
Closes #473
- Adding a dev container to be able to run the docs locally without installing Ruby and the GitHub Pages gem locally
- Including links to getting started with dev containers and learning more on dev containers
> Add a dev container to run the docs locally

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/TagWithEvaluator.cs
- src/Ardalis.Specification/Ardalis.Specification.csproj
- src/Ardalis.Specification/Builders/Builder_TagWith.cs
- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/Internals/OneOrMany.cs
- src/Ardalis.Specification/OneOrMany.cs
- src/Ardalis.Specification/Specification.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/TagWithEvaluatorTests.cs
- tests/Ardalis.Specification.Tests/Builders/Builder_TagWith.cs
- tests/Ardalis.Specification.Tests/Internals/OneOrManyTests.cs
- tests/Ardalis.Specification.Tests/SpecificationExtensionsTests.cs
Fixes #468 
We could implement this by simply holding a `List<string>` state in the specification. However, the memory overhead of a non-empty list is 72 bytes (on x64). Considering that in 99% of cases, users will add a single tag, the memory overhead is unacceptable. 
Instead, we'll create and use `OneOrMany` struct implementation, which has a single `object?` state (spending only 8 bytes for the reference). The state will represent a `string` or `List<string` depending on the situation.
> Add support for multiple TagWith

- src/Ardalis.Specification.EntityFramework6/Extensions/DbSetExtensions.cs
- src/Ardalis.Specification.EntityFramework6/RepositoryBaseOfT.cs
- src/Ardalis.Specification.EntityFrameworkCore/ContextFactoryRepositoryBaseOfT.cs
- src/Ardalis.Specification.EntityFrameworkCore/Extensions/DbSetExtensions.cs
- src/Ardalis.Specification.EntityFrameworkCore/RepositoryBaseOfT.cs
- src/Ardalis.Specification/CollectionExtensions.cs
- src/Ardalis.Specification/Evaluators/InMemorySpecificationEvaluator.cs
Added `AsList` extension. If the `IEnumerable` source is a `List`, we return the list, otherwise, we create a new one.
The `PostProcessingAction` is a `Func<IEnumerable<T>, IEnumerable<T>>` delegate. However, users do not always filter the collection; they may just iterate over it and update items. In that case, if the delegate output is `List`, we may directly return it instead of allocating a new one.
> Avoid List allocation for PostProcessingAction.

- .github/workflows/build.yml
- .github/workflows/ci.yml
- Ardalis.Specification.sln
Added new workflow that collects and publishes coverage reports. For now, we'll publish them just as markdown in the job summary page. Also modified the triggers as follows:
- `ci.yml` - it will be triggered for pull requests only. It builds and tests.
- `build.yml` - it will be triggered on push to main. It builds, tests, generates a coverage report, and publishes to the job summary page.
> Added Full Build workflow that publishes coverage reports.

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/IncludeEvaluator.cs
- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/IncludeStringEvaluator.cs
- src/Ardalis.Specification/Specification.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/IncludeEvaluatorTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/IncludeStringEvaluatorTests.cs
> Refactor the state of include expressions as OneOrMany.

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/QueryTagEvaluator.cs
- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SpecificationEvaluator.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/QueryTagEvaluatorTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/SpecificationEvaluatorTests.cs
The `TagWithEvaluator` is a weird name. It will be a minor breaking change for those using partial evaluators directly, but it was introduced relatively recently. Let's rename it now before it gets stuck forever.
> Rename TagWithEvaluator to QueryTagEvaluator.

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SearchEvaluator.cs
- src/Ardalis.Specification/Evaluators/SearchMemoryEvaluator.cs
- src/Ardalis.Specification/Internals/OneOrMany.cs
- src/Ardalis.Specification/Validators/SearchValidator.cs
- tests/Ardalis.Specification.Tests/Internals/OneOrManyTests.cs
> Consolidate OneOrMany implementation and its usage.

- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SearchEvaluator.cs
- src/Ardalis.Specification.EntityFrameworkCore/Evaluators/SearchExtension.cs
- src/Ardalis.Specification/Ardalis.Specification.csproj
- src/Ardalis.Specification/Evaluators/SearchMemoryEvaluator.cs
- src/Ardalis.Specification/Validators/SearchValidator.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/SearchEvaluatorCustomSpecTests.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/SearchExtensionTests.cs
- tests/Ardalis.Specification.Tests/Evaluators/SearchMemoryEvaluatorCustomSpecTests.cs
- tests/Ardalis.Specification.Tests/Validators/SearchValidatorCustomSpecTests.cs
This is just to cover the case where users have a custom `ISpecification<T>` implementation but use our evaluator.
It's highly unlikely that anyone does that, but we'll add a fallback to LINQ for the sake of completeness.
> Add a fallback to LINQ for search evaluators/validator in case of custom user specifications.

- src/Ardalis.Specification/ISpecification.cs
- src/Ardalis.Specification/Specification.cs
- src/Ardalis.Specification/SpecificationExtensions.cs
- tests/Ardalis.Specification.EntityFrameworkCore.Tests/Evaluators/SearchEvaluatorCustomSpecTests.cs
- tests/Ardalis.Specification.Tests/Evaluators/SearchMemoryEvaluatorCustomSpecTests.cs
- tests/Ardalis.Specification.Tests/SpecificationTests.cs
- tests/Ardalis.Specification.Tests/Validators/SearchValidatorCustomSpecTests.cs
> Redefine WithProjectionOf as an extension to Specification instead of ISpecification
